### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by azlandoctor2u** [MOLPay/molpay-mobile-xdk-android#7]
I received this from our app crash analytic. Can anyone give advice on how to avoid this in the future? This happened to our client on Samsung Galaxy Note 3 with OS Version 5.0.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String)' on a null object reference
       at com.molpay.molpayxdk.MOLPayActivity$MPMainUIWebClient.shouldOverrideUrlLoading(SourceFile:282)
       at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:356)
       at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:257)
       at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(SystemMessageHandler.java)
       at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)`

**Comment by clewlb** [comment]
@azlandoctor2u, thanks for reaching out, please update to V3.7.2. We have this fixed on the latest version, https://github.com/MOLPay/molpay-mobile-xdk-android/releases/tag/3.7.2
